CREATE DATABASE QLShopQuanAo
GO
USE QLShopQuanAo
GO
-- san pham
-- danh muc
-- tai khoan
-- hoa don
-- chi tiet hoa don
-- nhap kho
go
CREATE TABLE TAIKHOAN
(
	tenHienThiNV NVARCHAR(100) NOT NULL PRIMARY KEY,
	tenNV NVARCHAR(100) NOT NULL,
	matKhau NVARCHAR(1000) NOT NULL DEFAULT 0,
	loaiTK INT NOT NULL -- 1 LA NV, 0 LA ADMIN
)
GO

CREATE TABLE DANHMUC
(
	maDM INT IDENTITY PRIMARY KEY,
	tenDM NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên'
)
GO
CREATE TABLE SANPHAM
(
	maSP INT IDENTITY PRIMARY KEY,
	tenSP NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	maDM INT NOT NULL,
	gia FLOAT NOT NULL, 
	soLuong INT NOT NULL,
	Constraint FK_maDM Foreign key(maDM) references  DANHMUC(maDM)
)
GO
CREATE TABLE HOADON
(
	maHD INT IDENTITY PRIMARY KEY,
	ngay DATE NOT NULL,
	sdtKH VARCHAR(20) NOT NULL,
	tenKH NVARCHAR(100) NOT NULL,
)
GO
CREATE TABLE CHITIETHD 
(
	ID INT IDENTITY PRIMARY KEY,
	maHD INT NOT NULL,
	maSP INT NOT NULL,
	soLuong INT NOT NULL,
	Constraint FK_maHD Foreign key(maHD) references  HOADON(maHD),
	Constraint FK_maSP Foreign key(maSP) references  SANPHAM(maSP)
)
GO
CREATE TABLE NHAPKHO
(
	ID INT IDENTITY PRIMARY KEY,
	maSP INT NOT NULL,
	soLuong INT NOT NULL,
	donGia int not null,
	ngay Date NOT NULL,
	--FOREIGN KEY (maSP) REFERENCES DBO.SANPHAM (maSP)
)
GO
---
INSERT INTO TAIKHOAN VALUES (N'ADMIN',N'Pham Thi Linh',N'123',0)
INSERT INTO TAIKHOAN VALUES (N'STAFF',N'Nguyen Anh',N'321',1)
INSERT INTO TAIKHOAN VALUES (N'Nam',N'Le Nam',N'321',1)


INSERT INTO DANHMUC VALUES (N'Áo')
INSERT INTO DANHMUC VALUES (N'Quần')
INSERT INTO DANHMUC VALUES (N'Giày')

INSERT INTO SANPHAM VALUES (N'Áo croptop CR12',1,90000,100)
INSERT INTO SANPHAM VALUES (N'Giày gucci J42',3,2200000,150)
INSERT INTO SANPHAM VALUES (N'Quần jean ống rộng J34',2,230000,200)

INSERT INTO HOADON VALUES (getdate(),'0394106977',N'TRAN THI HANG')
INSERT INTO HOADON VALUES ('2021-08-25','0336948797',N'NGUYEN DIU')
INSERT INTO HOADON VALUES ('2021-08-29','033694457',N'LAN ANH')

INSERT INTO CHITIETHD VALUES (1,1,2)
INSERT INTO CHITIETHD VALUES (1,2,1)
INSERT INTO CHITIETHD VALUES (2,3,1)
INSERT INTO CHITIETHD VALUES (3,1,1)

INSERT INTO NHAPKHO VALUES (3,10,200000,getdate())
INSERT INTO NHAPKHO VALUES (1,50,70000,'2021-08-25')

   
SELECT * FROM DANHMUC
SELECT * FROM HOADON
SELECT * FROM CHITIETHD
SELECT * FROM SANPHAM
SELECT * FROM NHAPKHO
SELECT * FROM TAIKHOAN
---
--select * from HOADON where ngay>='20210829' and ngay<='20210901'

--cap nhat tai khoan (form thông tin cá nhân)
go
CREATE PROC CAPNHATTK
@Tenht nvarchar(100), @tennv nvarchar(100), @mk nvarchar(1000), @mkm nvarchar(1000)
as
begin
	DECLARE @mkDung int =0
	select @mkDung =count(*) from TAIKHOAN WHERE tenHienThiNV=@tenht AND matKhau=@mk

	IF(@mkDung=1)
	BEGIN
		IF(@mkm= NULL OR @mkm='')
		BEGIN
			UPDATE TAIKHOAN SET tenNV=@tennv WHERE tenHienThiNV=@Tenht
		END
		ELSE
			UPDATE TAIKHOAN SET tenNV=@tennv , matKhau=@mkm WHERE tenHienThiNV=@Tenht
	END
end
go
--
DELETE  CHITIETHD WHERE maSP=4



DELETE dbo.DANHMUC WHERE maDM=1
DELETE from CHITIETHD WHERE maSP=3
DELETE SANPHAM WHERE maDM = 3
DELETE dbo.DANHMUC WHERE maDM=1

-- cần xóa thêm bản ghi của bảng khác nếu khóa chính của bảng định xóa, xuất hiện làm khóa ngoại của 